/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef MAIN_H
#define MAIN_H

#include "graphics.h"

#include <string>

namespace GUI_Core {
    class Greeter {
        public:
        std::string greeting();
    };
}

#endif
